#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from evaluate_v46_stochastic import aggregate,evaluate_record,qualification,read
from v46_stochastic import mechanic_registry
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v46-oracle-stochastic-transitions/development/result.json"); p.add_argument("--audit",default="outputs/v46-oracle-stochastic-transitions/post-result-audit.json"); p.add_argument("--markdown",default="docs/v46-results.md"); a=p.parse_args(); result_path,audit_path,markdown=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); seal_path=PROJECT_ROOT/result["corpus_seal"]; seal=json.loads(seal_path.read_text()); impl_path=PROJECT_ROOT/seal["implementation_lock"]; impl=json.loads(impl_path.read_text()); records=[]
 for artifact in seal["corpora"].values(): records.extend(read(PROJECT_ROOT/artifact["path"]))
 records.sort(key=lambda x:x["id"]); registry=mechanic_registry(); reproduced=aggregate([evaluate_record(x,registry)[0] for x in records]); qualified=qualification(reproduced,impl["config_payload"]["gates"]); reproduction={"metrics":reproduced==result["metrics"],"qualification":qualified==result["qualification"],"predictions_hash":file_sha256(PROJECT_ROOT/result["predictions"])==result["predictions_sha256"]}; access=result["data_access"]; integrity={"one_oracle_development_run":access["oracle_development_runs"]==1,"no_selection":access["selection_on_development_evaluation"]==0,"no_sampled_realizations":access["sampled_realizations"]==0,"no_model_access":access["model_forward_passes"]==0,"no_training":access["adapter_training_runs"]==0,"implementation_bound":seal["implementation_lock_sha256"]==file_sha256(impl_path),"seal_bound":result["corpus_seal_sha256"]==file_sha256(seal_path),"non_final":seal["authorization"]["final_evaluations"]==0}; errors=[]
 if not all(reproduction.values()): errors.append("V46 result does not reproduce")
 if not all(integrity.values()): errors.append("V46 firewall or lock chain failed")
 audit={"schema_version":46,"experiment":"v46_post_result_audit","passed":not errors,"decision":"accept_v46_oracle_development" if not errors else "reject_v46_oracle_development","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"integrity_checks":integrity,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n"); m=result["metrics"]
 markdown.write_text("\n".join(["# V46 results: oracle stochastic-transition foundation","",f"Decision: `{result['decision']}`.","","V46 is a language-free, non-final oracle development result. It tests exact probability semantics and distribution-valued mechanic induction; it does not test estimation from sampled outcomes.","","| Metric | Result |","|---|---:|",f"| Oracle program validation | {m['oracle_program_validation']:.3f} |",f"| Exact mass normalization | {m['mass_normalization']:.3f} |",f"| Weighted target retention | {m['weighted_target_retention']:.3f} |",f"| Weighted schema recovery | {m['weighted_schema_recovery']:.3f} |",f"| Exact trajectory-distribution match | {m['exact_trajectory_distribution_match']:.3f} |",f"| Mean trajectory total variation | {m['mean_trajectory_total_variation']:.3f} |",f"| Uniformized-support control | {m['uniformized_exact_distribution_match']:.3f} |",f"| MAP-determinized control | {m['map_exact_distribution_match']:.3f} |",f"| Literal distribution lookup | {m['literal_lookup_exact_distribution_match']:.3f} |","",f"All preregistered gates passed: `{str(result['qualification']['passed']).lower()}`.","",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`.","","A pass authorizes preregistration only of a fresh sampled-transition probability-estimation stage with calibration and proper scoring. Language, active selection, open ontology, and final evaluation remain deferred."])+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
