#!/usr/bin/env python3
"""Reproduce, audit, and summarize the V41 confirmation."""
from __future__ import annotations
import argparse,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from evaluate_v41_confirmation import aggregate,read,score_record
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v41-relational-mechanic-confirmation/evaluation/result.json"); p.add_argument("--audit",default="outputs/v41-relational-mechanic-confirmation/post-result-audit.json"); p.add_argument("--markdown",default="docs/v41-results.md"); a=p.parse_args(); result_path,audit_path,md=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); seal_path=PROJECT_ROOT/result["corpus_seal"]; seal=json.loads(seal_path.read_text()); impl_path=PROJECT_ROOT/seal["implementation_lock"]; impl=json.loads(impl_path.read_text()); records=read(PROJECT_ROOT/seal["corpus"]["path"]); reproduced=aggregate([score_record(r,impl["v22_config_payload"],impl["v32_config_payload"])[0] for r in records]); reproduction={"metrics":reproduced==result["metrics"],"predictions_hash":file_sha256(PROJECT_ROOT/result["predictions"])==result["predictions_sha256"]}; access=result["data_access"]; integrity={"one_confirmation":access["confirmation_evaluations"]==1,"no_selection":access["selection_on_confirmation"]==0,"no_model_access":access["model_forward_passes"]==0,"no_v22r2_evaluation":access["v22r2_evaluation_records_read"]==0,"no_v28":access["v28_runs"]==0,"no_adapter":access["adapter_training_runs"]==0,"compiler_unchanged":file_sha256(PROJECT_ROOT/impl["frozen_compiler"])==impl["frozen_compiler_sha256"],"kernel_unchanged":file_sha256(PROJECT_ROOT/impl["frozen_semantic_kernel"])==impl["frozen_semantic_kernel_sha256"],"implementation_bound":seal["implementation_lock_sha256"]==file_sha256(impl_path),"seal_bound":result["corpus_seal_sha256"]==file_sha256(seal_path)}; errors=[]
 if not all(reproduction.values()): errors.append("V41 result does not reproduce")
 if not all(integrity.values()): errors.append("V41 firewall or lock chain failed")
 audit={"schema_version":41,"experiment":"v41_post_result_audit","passed":not errors,"decision":"accept_v41_confirmation" if not errors else "reject_v41_confirmation","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"integrity_checks":integrity,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n"); m=result["metrics"]
 lines=["# V41 results: declared-scope relational-mechanic confirmation","",f"Decision: `{result['decision']}`.","","The frozen compiler and frozen V22 symbolic kernel were evaluated once on 40 unseen lifted mechanics.","","| Metric | Result |","|---|---:|",f"| Clause exact parse | {m['clause_exact_parse']:.3f} |",f"| Support exact graph | {m['support_exact_graph']:.3f} |",f"| Query exact graph | {m['query_exact_graph']:.3f} |",f"| Schema recovery | {m['schema_recovery']:.3f} |",f"| Target retention | {m['target_retention']:.3f} |",f"| Empty version space | {m['empty_version_space']:.3f} |",f"| Transition-set exact | {m['transition_set_exact']:.3f} |",f"| Complete-episode exact | {m['complete_episode_exact']:.3f} |",f"| Empirical lookup exact | {m['empirical_lookup_transition_set_exact']:.3f} |","",f"All preregistered gates passed: `{str(result['qualification']['passed']).lower()}`.","","Interpretation: within the declared one-step Boolean relational scope, the language-to-symbol interface and lifted schema inducer now have a population-level end-to-end confirmation. This does not establish open language or general world-model learning. The next research stage should deliberately break the current architecture with sequential mutation, stochastic or delayed effects, active intervention choice, and open concepts.","",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`."]
 md.write_text("\n".join(lines)+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
