#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from evaluate_v47_sampled import aggregate,evaluate_record,qualification,read
from v47_sampling import mechanic_registry
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v47-sampled-transition-estimation/development/result.json"); p.add_argument("--audit",default="outputs/v47-sampled-transition-estimation/post-result-audit.json"); p.add_argument("--markdown",default="docs/v47-results.md"); a=p.parse_args(); result_path,audit_path,markdown=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); seal_path=PROJECT_ROOT/result["corpus_seal"]; seal=json.loads(seal_path.read_text()); impl_path=PROJECT_ROOT/seal["implementation_lock"]; impl=json.loads(impl_path.read_text()); records=[]
 for artifact in seal["corpora"].values(): records+=read(PROJECT_ROOT/artifact["path"])
 registry=mechanic_registry(); budgets=impl["config_payload"]["population"]["nestedTrialsPerIntervention"]; reproduced=aggregate([evaluate_record(x,registry,budgets) for x in sorted(records,key=lambda x:x["id"])],budgets); q=qualification(reproduced,impl["config_payload"]["gatesAt128TrialsPerIntervention"]); reproduction={"metrics":reproduced==result["metrics"],"qualification":q==result["qualification"],"mechanic_metrics_hash":file_sha256(PROJECT_ROOT/result["mechanic_metrics"])==result["mechanic_metrics_sha256"]}; access=result["data_access"]; integrity={"one_run":access["sampled_development_runs"]==1,"no_selection":access["selection_on_development_evaluation"]==0,"no_model":access["model_forward_passes"]==0,"no_training":access["adapter_training_runs"]==0,"implementation_bound":seal["implementation_lock_sha256"]==file_sha256(impl_path),"seal_bound":result["corpus_seal_sha256"]==file_sha256(seal_path),"non_final":seal["authorization"]["final_evaluations"]==0}; errors=[]
 if not all(reproduction.values()): errors.append("V47 result does not reproduce")
 if not all(integrity.values()): errors.append("V47 lock or firewall failed")
 audit={"schema_version":47,"experiment":"v47_post_result_audit","passed":not errors,"decision":"accept_v47_sampled_development" if not errors else "reject_v47_sampled_development","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"integrity_checks":integrity,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n"); m=result["metrics"]; x=m["128"]; markdown.write_text("\n".join(["# V47 results: sampled transition-probability estimation","",f"Decision: `{result['decision']}`.","","V47 tests finite-sample estimation from realized trajectories under a declared ontology, DSL, and finite probability vocabulary. It is non-final and language-free.","","| Metric at 128 trials/intervention | Result |","|---|---:|",f"| Mean joint-distribution TV | {x['mean_joint_distribution_tv']:.4f} |",f"| Probability parameter MAE | {x['probability_parameter_mae']:.4f} |",f"| MAP schema recovery | {x['map_schema_recovery']:.3f} |",f"| Mean target-program posterior | {x['mean_target_program_posterior']:.3f} |",f"| Held-out trajectory log loss | {x['heldout_log_loss']:.4f} |",f"| Calibration error | {x['calibration_error']:.4f} |",f"| Improvement over uniformized | {x['log_loss_improvement_over_uniformized']:.4f} nats |","",f"Mean TV learning curve: 8 = {m['8']['mean_joint_distribution_tv']:.4f}, 32 = {m['32']['mean_joint_distribution_tv']:.4f}, 128 = {m['128']['mean_joint_distribution_tv']:.4f}.","",f"All preregistered gates passed: `{str(result['qualification']['passed']).lower()}`.",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`."])+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
