#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from evaluate_v43_language import read
from evaluate_v43r1_repair import compute,qualify
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v43r1-graph-measurement-repair/rescore/result.json"); p.add_argument("--audit",default="outputs/v43r1-graph-measurement-repair/post-result-audit.json"); p.add_argument("--markdown",default="docs/v43r1-results.md"); a=p.parse_args(); result_path,audit_path,markdown=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); lock_path=PROJECT_ROOT/result["implementation_lock"]; lock=json.loads(lock_path.read_text()); outcome_path=PROJECT_ROOT/lock["source_v43_outcome_lock"]; outcome=json.loads(outcome_path.read_text()); original_result=json.loads((PROJECT_ROOT/outcome["result"]).read_text()); seal=json.loads((PROJECT_ROOT/lock["source_v43_corpus_seal"]).read_text()); records=[]
 for artifact in seal["corpora"].values(): records.extend(read(PROJECT_ROOT/artifact["path"]))
 records.sort(key=lambda x:x["id"]); original={"metrics":original_result["metrics"],"gate_checks":original_result["qualification"]["checks"],"registered_gates":lock["v43_registered_gates"]}; metrics=compute(records,original); qualification=qualify(metrics,lock["config_payload"]["gates"]); reproduction={"metrics":metrics==result["metrics"],"qualification":qualification==result["qualification"]}; integrity={"one_repair_rescore":result["data_access"]["repair_rescores"]==1,"no_new_corpus":result["data_access"]["new_corpus_records"]==0,"no_model_access":result["data_access"]["model_forward_passes"]==0,"no_training":result["data_access"]["adapter_training_runs"]==0,"original_v43_unchanged":file_sha256(PROJECT_ROOT/outcome["result"])==outcome["result_sha256"],"implementation_bound":result["implementation_lock_sha256"]==file_sha256(lock_path)}; errors=[]
 if not all(reproduction.values()): errors.append("V43r1 rescore does not reproduce")
 if not all(integrity.values()): errors.append("V43r1 lock or firewall failed")
 audit={"schema_version":"43r1","experiment":"v43r1_post_result_audit","passed":not errors,"decision":"accept_v43r1_measurement_repair" if not errors else "reject_v43r1_measurement_repair","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"integrity_checks":integrity,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n")
 m=result["metrics"]; markdown.write_text("\n".join(["# V43r1 results: graph measurement repair","",f"Decision: `{result['decision']}`.","","V43's original failed outcome remains immutable. V43r1 is a preregistered correction over the same paired development data, not an independent replication.","","| Metric | Result |","|---|---:|",f"| Original ordered-list graph exact | {m['original_registered_ordered_graph_exact']:.3f} |",f"| Repaired canonical graph exact ({m['graph_pairs']} graphs) | {m['canonical_graph_exact']:.3f} |",f"| Duplicate-free | {m['duplicate_free']:.3f} |",f"| Semantic content mismatches | {m['semantic_content_mismatches']} |",f"| Comparator permutation invariance | {m['comparator_permutation_invariance']:.3f} |",f"| Other V43 metrics reproduced | {m['other_v43_metrics_reproduced']:.3f} |",f"| Other V43 gates passed | {m['other_v43_gate_checks_passed']:.3f} |","",f"All repair gates passed: `{str(result['qualification']['passed']).lower()}`.","",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`."])+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
