#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from evaluate_v48_composition import aggregate,evaluate_record,qualification,read
from v48_composition import mechanic_registry
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v48-stochastic-language-composition/development/result.json"); p.add_argument("--audit",default="outputs/v48-stochastic-language-composition/post-result-audit.json"); p.add_argument("--markdown",default="docs/v48-results.md"); a=p.parse_args(); result_path,audit_path,markdown=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); seal_path=PROJECT_ROOT/result["corpus_seal"]; seal=json.loads(seal_path.read_text()); impl_path=PROJECT_ROOT/seal["implementation_lock"]; impl=json.loads(impl_path.read_text()); records=[]
 for artifact in seal["corpora"].values(): records+=read(PROJECT_ROOT/artifact["path"])
 registry=mechanic_registry(); reproduced=aggregate([evaluate_record(x,registry) for x in sorted(records,key=lambda x:x["id"])]); q=qualification(reproduced,impl["config_payload"]["gates"]); reproduction={"metrics":reproduced==result["metrics"],"qualification":q==result["qualification"],"mechanic_metrics_hash":file_sha256(PROJECT_ROOT/result["mechanic_metrics"])==result["mechanic_metrics_sha256"]}; access=result["data_access"]; reporting=json.loads(PROJECT_ROOT.joinpath(impl["reporting_supplement_lock"]).read_text()); integrity={"one_run":access["development_runs"]==1,"no_selection":access["selection_on_development_evaluation"]==0,"no_model":access["model_forward_passes"]==0,"no_training":access["adapter_training_runs"]==0,"implementation_bound":seal["implementation_lock_sha256"]==file_sha256(impl_path),"seal_bound":result["corpus_seal_sha256"]==file_sha256(seal_path),"reporting_bound":impl["reporting_supplement_lock_sha256"]==file_sha256(PROJECT_ROOT/impl["reporting_supplement_lock"]),"reporting_non_gating":reporting["non_gating"],"non_final":seal["authorization"]["final_evaluations"]==0}; errors=[]
 if not all(reproduction.values()): errors.append("V48 result does not reproduce")
 if not all(integrity.values()): errors.append("V48 lock or firewall failed")
 audit={"schema_version":48,"experiment":"v48_post_result_audit","passed":not errors,"decision":"accept_v48_composition_development" if not errors else "reject_v48_composition_development","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"integrity_checks":integrity,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n"); m=result["metrics"]; x=m["all_mechanics"]; l=x["language"]; markdown.write_text("\n".join(["# V48 results: stochastic language composition","",f"Decision: `{result['decision']}`.","","V48 is a non-final paired composition test. It does not test open language, probability language, passive partial observation, or active intervention selection.","","| Metric | Language | Matched symbolic |","|---|---:|---:|",f"| Mean joint-distribution TV | {l['mean_tv']:.6g} | {x['symbolic']['mean_tv']:.6g} |",f"| Held-out trajectory log loss | {l['heldout_log_loss']:.6f} | {x['symbolic']['heldout_log_loss']:.6f} |",f"| Calibration error | {l['calibration_error']:.6f} | {x['symbolic']['calibration_error']:.6f} |",f"| MAP schema recovery | {l['map_schema_recovery']:.3f} | {x['symbolic']['map_schema_recovery']:.3f} |",f"| Mean target posterior | {l['mean_target_program_posterior']:.6f} | {x['symbolic']['mean_target_program_posterior']:.6f} |","",f"Language-minus-symbolic TV: `{x['language_minus_symbolic_tv']:.6g}`.",f"Language-minus-symbolic log loss: `{x['language_minus_symbolic_log_loss']:.6g}`.",f"Exact trial alignment: `{m['interface']['trial_alignment_exact']:.3f}`.",f"Worst mechanic: `{x['worst_mechanic']['id']}` at TV `{x['worst_mechanic']['tv']:.6g}`.",f"Worst family: `{x['worst_family']}`; probability: `{x['worst_probability']}`; timing: `{x['worst_timing']}`; length: `{x['worst_sequence_length']}`.","",f"All preregistered gates passed: `{str(result['qualification']['passed']).lower()}`.",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`."])+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
