#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from evaluate_v44_delayed import aggregate,evaluate_record,qualification,read
from v44_delayed import mechanic_registry
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v44-deterministic-delayed-effects/development/result.json"); p.add_argument("--audit",default="outputs/v44-deterministic-delayed-effects/post-result-audit.json"); p.add_argument("--markdown",default="docs/v44-results.md"); a=p.parse_args(); result_path,audit_path,markdown=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); seal_path=PROJECT_ROOT/result["corpus_seal"]; seal=json.loads(seal_path.read_text()); impl_path=PROJECT_ROOT/seal["implementation_lock"]; impl=json.loads(impl_path.read_text()); records=[]
 for artifact in seal["corpora"].values(): records.extend(read(PROJECT_ROOT/artifact["path"]))
 records.sort(key=lambda x:x["id"]); registry=mechanic_registry(); reproduced=aggregate([evaluate_record(x,registry)[0] for x in records]); q=qualification(reproduced,impl["config_payload"]["gates"]); reproduction={"metrics":reproduced==result["metrics"],"qualification":q==result["qualification"],"predictions_hash":file_sha256(PROJECT_ROOT/result["predictions"])==result["predictions_sha256"]}; access=result["data_access"]; integrity={"one_oracle_development_run":access["oracle_development_runs"]==1,"no_selection":access["selection_on_development_evaluation"]==0,"no_model_access":access["model_forward_passes"]==0,"no_training":access["adapter_training_runs"]==0,"no_v43_record_reuse":access["v43_records_read"]==0,"implementation_bound":seal["implementation_lock_sha256"]==file_sha256(impl_path),"seal_bound":result["corpus_seal_sha256"]==file_sha256(seal_path),"non_final":seal["authorization"]["final_evaluations"]==0}; errors=[]
 if not all(reproduction.values()): errors.append("V44 result does not reproduce")
 if not all(integrity.values()): errors.append("V44 firewall or lock chain failed")
 audit={"schema_version":44,"experiment":"v44_post_result_audit","passed":not errors,"decision":"accept_v44_oracle_development" if not errors else "reject_v44_oracle_development","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"integrity_checks":integrity,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n"); m=result["metrics"]; markdown.write_text("\n".join(["# V44 results: oracle deterministic delayed effects","",f"Decision: `{result['decision']}`.","","V44 is a language-free, non-final development result testing a hidden deterministic event queue.","","| Metric | Result |","|---|---:|",f"| Oracle program validation | {m['oracle_program_validation']:.3f} |",f"| Queued target retention | {m['queued_target_retention']:.3f} |",f"| Queued schema recovery | {m['queued_schema_recovery']:.3f} |",f"| Queued next-state exact | {m['queued_next_state_exact']:.3f} |",f"| Queued final-observation exact | {m['queued_final_observation_exact']:.3f} |",f"| Wait-placement counterfactual accuracy | {m['wait_placement_counterfactual_accuracy']:.3f} |",f"| Collapsed-delay control | {m['collapsed_delay_final_exact']:.3f} |",f"| End-flush control | {m['end_flush_final_exact']:.3f} |",f"| Literal lookup | {m['literal_lookup_final_exact']:.3f} |","",f"All preregistered gates passed: `{str(result['qualification']['passed']).lower()}`.","",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`."])+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
