#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
import numpy as np
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
from v38_focus_parser import extract_literal_candidates
from v38_evaluation import qualification,score,select_method
def read(path): return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
def main():
 p=argparse.ArgumentParser(); p.add_argument("--result",default="outputs/v38-ontology-anchored-focus-parser/evaluation/result.json"); p.add_argument("--audit",default="outputs/v38-ontology-anchored-focus-parser/post-result-audit.json"); p.add_argument("--markdown",default="docs/v38-results.md"); a=p.parse_args(); result_path,audit_path,md=tuple((PROJECT_ROOT/x).resolve() for x in (a.result,a.audit,a.markdown)); result=json.loads(result_path.read_text()); fl_path=PROJECT_ROOT/result["features_lock"]; fl=json.loads(fl_path.read_text()); seal=json.loads((PROJECT_ROOT/fl["corpus_seal"]).read_text()); impl_path=PROJECT_ROOT/seal["implementation_lock"]; impl=json.loads(impl_path.read_text()); rows=sorted(read(PROJECT_ROOT/seal["corpora"]["ontology_focus_validation"]["path"]),key=lambda r:r["id"]); predictions={r["id"]:r for r in read(PROJECT_ROOT/result["predictions"])}; indices=np.asarray([predictions[r["id"]]["selected_candidate_index"] for r in rows]); operations=[predictions[r["id"]]["outer_operation"] for r in rows]; candidates=[extract_literal_candidates(r) for r in rows]; metrics=score(rows,indices,candidates,operations,impl["v32_config_payload"]); qual=qualification(metrics,impl["config_payload"]); errors=[]
 reproduction={"metrics":metrics==result["selected_validation"],"qualification":qual==result["qualification"],"predictions_hash":file_sha256(PROJECT_ROOT/result["predictions"])==result["predictions_sha256"]}; selection=select_method(result["cv_reports"],impl["config_payload"]["selection"]["methods"])==result["focus_selection"]
 if not all(reproduction.values()) or not selection: errors.append("V38 result does not reproduce")
 meta=json.loads((PROJECT_ROOT/fl["feature_metadata"]).read_text()); access=result["data_access"]; checks={"one_validation":access["validation_evaluations"]==1,"no_validation_selection":access["selection_on_validation"]==0,"exact_forwards":meta["backbone_forward_passes"]==1280,"zero_truncation":meta["truncated_prompts"]==0,"no_v32_evaluation":access["v32_evaluation_records_read"]==0,"no_v28":access["v28_runs"]==0,"no_adapter":access["adapter_training_runs"]==0,"implementation_bound":seal["implementation_lock_sha256"]==file_sha256(impl_path)}
 if not all(checks.values()): errors.append("V38 firewall or lock chain failed")
 audit={"schema_version":38,"experiment":"v38_post_result_audit","passed":not errors,"decision":"accept_v38_result" if not errors else "reject_v38_result","errors":errors,"result":str(result_path.relative_to(PROJECT_ROOT)),"result_sha256":file_sha256(result_path),"reproduction_checks":reproduction,"selection_check":selection,"integrity_checks":checks,"scientific_decision":result["decision"]}; audit_path.parent.mkdir(parents=True,exist_ok=True); audit_path.write_text(json.dumps(audit,indent=2,sort_keys=True)+"\n")
 m=metrics; lines=["# V38 results: ontology-anchored focus parser","",f"Decision: `{result['decision']}`.","","V38 is a development-only constrained semantic-parser result.","","| Metric | Result |","|---|---:|",f"| Focus | {m['focus_accuracy']:.3f} |",f"| Lexical sign | {m['lexical_sign_accuracy']:.3f} |",f"| Outer operation (frozen V37 interface) | {m['outer_operation_accuracy']:.3f} |",f"| Compiled truth | {m['compiled_truth_accuracy']:.3f} |",f"| Focus first | {m['focus_first_accuracy']:.3f} |",f"| Focus second | {m['focus_second_accuracy']:.3f} |",f"| Exact-opposite decoy | {m['exact_opposite_decoy_accuracy']:.3f} |",f"| Different-atom decoy | {m['different_atom_decoy_accuracy']:.3f} |",f"| Worst surface family | {m['worst_surface_family_accuracy']:.3f} |","",f"Fit-only selected method: `{result['focus_selection']['method']}`. All gates passed: `{str(qual['passed']).lower()}`.","",f"Post-result integrity audit: `{'pass' if audit['passed'] else 'fail'}`."]; md.write_text("\n".join(lines)+"\n"); print(json.dumps(audit,indent=2,sort_keys=True));
 if not audit["passed"]: raise SystemExit(1)
if __name__=="__main__": main()
