#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from v10_protocol import file_sha256
from v22r2_grounding import PROJECT_ROOT
FILES=("python/v48_composition.py","python/generate_v48_composition.py","python/evaluate_v48_composition.py","python/test_v48_composition.py","python/audit_v48_implementation.py","python/freeze_v48_implementation.py","python/audit_v48_corpus.py","python/seal_v48_corpus.py","python/audit_and_summarize_v48.py","python/freeze_v48_outcome.py","python/v47_sampling.py","python/v46_stochastic.py","python/v45_language.py","python/v43_language.py","python/v43r1_measurement.py","python/v39_compiler.py","python/v42_stateful.py","python/v22_relational.py","python/v22r2_grounding.py","python/v10_protocol.py")
def main():
 p=argparse.ArgumentParser(); p.add_argument("--design-lock",default="configs/v48-design-lock.json"); p.add_argument("--reporting-lock",default="configs/v48-reporting-supplement-lock.json"); p.add_argument("--audit",default="outputs/v48-stochastic-language-composition/implementation-audit.json"); p.add_argument("--output",default="configs/v48-implementation-lock.json"); a=p.parse_args(); design,reporting,audit_path,output=tuple((PROJECT_ROOT/x).resolve() for x in (a.design_lock,a.reporting_lock,a.audit,a.output)); audit=json.loads(audit_path.read_text()); d=json.loads(design.read_text())
 if output.exists() or not audit["passed"] or audit["design_lock_sha256"]!=file_sha256(design) or audit["reporting_supplement_lock_sha256"]!=file_sha256(reporting): raise RuntimeError("Cannot freeze V48 implementation")
 for path in FILES:
  if not (PROJECT_ROOT/path).is_file(): raise RuntimeError(f"Missing {path}")
 count_keys=("mechanics","support_interventions","support_trials","queries","heldout_trials","state_clauses","action_commands","safety_challenges"); lock={"schema_version":48,"experiment":"v48_implementation_lock","design_lock":str(design.relative_to(PROJECT_ROOT)),"design_lock_sha256":file_sha256(design),"reporting_supplement_lock":str(reporting.relative_to(PROJECT_ROOT)),"reporting_supplement_lock_sha256":file_sha256(reporting),"implementation_audit":str(audit_path.relative_to(PROJECT_ROOT)),"implementation_audit_sha256":file_sha256(audit_path),"config_payload":d["config_payload"],"source_v47_outcome_lock":d["source_v47_outcome_lock"],"source_v47_outcome_lock_sha256":file_sha256(PROJECT_ROOT/d["source_v47_outcome_lock"]),"expected_corpus_sha256":audit["dry_run"]["expected_corpus_sha256"],"expected_counts":{k:audit["dry_run"][k] for k in count_keys},"implementation":{path:file_sha256(PROJECT_ROOT/path) for path in FILES},"authorization":{"construct_development_population":True,"run_development":False,"model_access":False}}; lock["lock_payload_sha256"]=hashlib.sha256(json.dumps(lock,sort_keys=True,separators=(",",":")).encode()).hexdigest(); output.write_text(json.dumps(lock,indent=2,sort_keys=True)+"\n"); print(json.dumps(lock,indent=2,sort_keys=True))
if __name__=="__main__": main()
